packages:
  - "apps/*"
  - "packages/*"
  - "packages/core/tests"
  - "packages/llamaflowjs/tests"
  - "packages/llamaflowjs/e2e"
  - "packages/llamaflowjs/e2e/examples/*"
  - "packages/autotool/examples/*"
  - "examples/"
  - "examples/*"
